theblog/comments/urls.py
from django.conf.urls import url

from .views import (
        comment_thread,
        comment_delete,
        comment_edit
)

urlpatterns = [
    url(r'^(?P<id>\d+)$', comment_thread, name='thread'),
    url(r'^(?P<id>\d+)/edit/$', comment_edit, name="edit"),
    url(r'^(?P<id>\d+)/delete/$', comment_delete, name="delete")
]

theblog/posts/urls.py
from django.conf.urls import url

from .views import (
        posts_create,
        posts_delete,
        posts_detail,
        posts_list,
        posts_update,
)

urlpatterns = [
    url(r'^$', posts_list, name='list'),
    url(r'^create/$', posts_create, name='create'),
    url(r'^(?P<slug>[\w-]+)$', posts_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', posts_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', posts_delete, name="delete")
]

theblog/src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import (login_view, register_view, logout_view)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^', include("posts.urls", namespace='posts')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theblog/comments/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse


class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id = obj_id).filter(parent=None)
        return qs


class Comment(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    parent      = models.ForeignKey("self", null=True,blank=True)
    content     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return str(self.user.username)

    def children(self):
        return Comment.objects.filter(parent=self)

    def get_absolute_url(self):
        id = self.id
        if not self.is_parent:
            id = self.parent.id
        return reverse("comments:thread", kwargs={"id": id})

    def get_delete_url(self):
        return reverse("comments:delete", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("comments:edit", kwargs={"id": self.id})

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

theblog/posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.text import slugify
from django.utils import timezone
from django.utils.text import mark_safe
from markdown_deux import markdown
from django.contrib.contenttypes.models import ContentType

from comments.models import Comment
from .utils import get_read_time

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


# Create your models here.
def upload_location(instance, filename):
    return "%s/%s" % (instance.slug, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to=upload_location,
                              null=True, blank=True,
                              height_field="height_field",
                              width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    slug = models.SlugField(unique=True)
    read_time = models.IntegerField(default=0)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("posts:delete", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("posts:update", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-update']

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance= self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance= self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_saved_post_receive(sender, instance,*args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time

pre_save.connect(pre_saved_post_receive, sender=Post)

theblog/comments/forms.py
from django import forms
from.models import Comment


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    # parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea)

theblog/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

theblog/comments/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse

from .models import Comment
from .forms import CommentForm
from posts.models import Post


@login_required
def comment_delete(request, id=None):
    try:
        obj = Comment.objects.get(id = id)
    except:
        raise Http404

    if obj.user != request.user:
        response = HttpResponse("You do not have permission to do this")
        response.status_code = 403
        return response

    if request.method == "POST":
        parent_object_url = obj.content_object.get_absolute_url()
        obj.delete()
        messages.success(request, "Successfully deleted")
        return HttpResponseRedirect(parent_object_url)

    context = {
        "object": obj,
        "title": "Delete comment",
    }
    return render(request, "confirm_delete.html", context)


@login_required
def comment_edit(request, id=None):
    try:
        obj = Comment.objects.get(id = id)
    except:
        raise Http404

    initial_data = {
        "content_type": obj.content_type,
        "object_id": obj.object_id,
        "content": obj.content
    }

    if obj.user != request.user:
        response = HttpResponse("You do not have permission to do this")
        response.status_code = 403
        return response

    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")

        Comment.objects.filter(id=id).update(
                content=content_data,
            )
        messages.success(request, "Successfully edited")
        return HttpResponseRedirect(obj.get_absolute_url())

    context = {
        "object": obj,
        "title": "Edit comment",
        "form": form
    }
    return render(request, "comment_form.html", context)


# Create your views here.
def comment_thread(request, id=None):
    try:
        obj = Comment.objects.get(id = id)
    except:
        raise Http404

    if not obj.is_parent:
        obj = obj.is_parent

    post_id = obj.object_id
    post = Post.objects.filter(id=post_id)
    post = post.first()

    initial_data = {
        "content_type": obj.content_type,
        "object_id": obj.object_id
    }

    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
                user=request.user,
                content_type=content_type,
                object_id=obj_id,
                content=content_data,
                parent=parent_obj
            )
        return HttpResponseRedirect(obj.get_absolute_url())

    context = {
        "comment": obj,
        "title": "Comment thread",
        "comment_form": form,
        "instance": post,

    }
    return render(request, "comment_thread.html", context)

theblog/posts/views.py
from urllib import parse


from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


# Create your views here.
from django.db.models.query_utils import Q

from comments.forms import CommentForm
from comments.models import Comment
from .models import Post
from .forms import PostForm


def posts_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, "Successfully Created")
            return HttpResponseRedirect(instance.get_absolute_url())
        else:
            messages.error(request, "Not Created")
    context = {
        "button_name": "Create post",
        "form": form,
        "title": "Create new post"
    }
    return render(request, "post_form.html", context)


def posts_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = parse.quote_plus(instance.content)

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }

    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
                user = request.user,
                content_type = content_type,
                object_id = obj_id,
                content = content_data,
                parent = parent_obj
            )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = instance.comments
    today = timezone.now().date()
    context = {
        "instance": instance,
        "share_string": share_string,
        "today": today,
        "comments": comments,
        "comment_form": form
    }
    return render(request, 'post_detail.html', context)


def posts_list(request):
    queryset_list = Post.objects.active()
    if request.user.is_superuser or request.user.is_staff:
        queryset_list = Post.objects.all()

    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
        )
    qs_length = len(queryset_list)
    paginator = Paginator(queryset_list, 10) # Show 10 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    today = timezone.now().date()

    context = {
        "len": qs_length,
        "queryset": queryset,
        "page_request_var": page_request_var,
        "today": today
    }
    return render(request, 'posts_list.html', context)


def posts_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Saved")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "button_name": "Edit post",
        "title": "Edit post",
        "instance": instance,
        "form": form
    }
    return render(request, 'post_form.html', context)


def posts_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        instance.delete()
        messages.success(request, "Successfully deleted")
        return HttpResponseRedirect("/")

    context = {
        "object": instance,
        "title": "Delete post",
    }
    return render(request, "confirm_delete.html", context)

theblog/templates/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}The Blog{% endblock title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" type="image/gif" href="https://www.iconattitude.com/icons/open_icon_library/apps/png/256/gnome-blog.png">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../static/css/navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../static/js/ie-emulation-modes-warning.js"></script>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block head_extra %}{% endblock head_extra %}
</head>

<body>

{% include 'messages.html' %}

<div class="container">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "posts:list" %}">The Blog</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url "posts:list" %}">Home</a></li>
                    {% block post_detail_link %}
                    {% endblock %}
                    {% if request.user.is_staff or  equest.user.is_superuser %}
                        <li><a href="{% url "posts:create" %}">New post</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url "logout" %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url "register" %}">Register</a></li>
                        <li><a href="{% url "login" %}">Login</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

{% block content %}


{% endblock content %}
</div>


<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v2.6";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- jQuery -->
<script   src="http://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>

<script src="../static/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../static/js/ie10-viewport-bug-workaround.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text();
            var markedContent = marked(content);
            $(this).html(markedContent);
        });
        $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive");
        });


        $(".comment-reply-btn").click(function(event){
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
        })

        var contentItem = $("#id_content");
        function setContent(value) {
            var markedContent = marked(value);
            $("#preview-content").html(markedContent);
            $("#preview-content img").each(function(){
                $(this).addClass("img-responsive");
            })
        }
        setContent(contentItem.val().replace(/\n/g, "<br>\n"));

        contentItem.keyup(function(){
            content = $(this).val();
            new_content = content.replace(/\n/g, "<br>\n");
            console.log(new_content);
            setContent(new_content)
        });

        var titleItem = $("#id_title");
        function setTitle(value) {
            var markedTitle = marked(value);
            $("#preview-title").html(markedTitle);
        }
        setTitle(titleItem.val());

        titleItem.keyup(function(){
            new_title = $(this).val();
            setTitle(new_title)
        });
    })
</script>
</body>
</html>

theblog/templates/comment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
{{title}} |{{ block.super }}
{% endblock title %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3">
    <h1>Form</h1>
    <form method="post" action="" enctype="multipart/form-data"> {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Edit comment"/>
        <a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
    </form>
</div>

{% endblock content %}

theblog/templates/comment_thread.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}
{{ title }} |{{ block.super }}
{% endblock title %}

{% block post_detail_link %}
    <li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
        <h3>{{ comment.content|linebreaks }}</h3>
        <footer> via {{ comment.user }} | {{ comment.timestamp|timesince }} ago
            {% if comment.children.count > 0 %}| {{ comment.children.count }}
                Comment{% if comment.children.count > 1 %}s{% endif %}
            {% endif %}
            {% if comment.user == request.user %}
                | <a href="{{ comment.get_edit_url }}">Edit</a>
            {% endif %}
            {% if comment.user == request.user %}
                | <a href="{{ comment.get_delete_url }}">Delete</a>
            {% endif %}
        </footer>
        <hr>
        {% if request.user.is_authenticated %}
        <form method="post" action=""> {%  csrf_token %}
            {{ comment_form|crispy }}
            <input type="hidden" name="parent_id" value="{{ comment.id }}"/>
            <input type="submit" value="Reply" class="btn btn-default"/>
        </form>
        {% else %}
            <p>You must login to comment</p>
        {% endif %}

        {%  for child_comment in comment.children %}
        <blockquote>
            <p>{{ child_comment.content|linebreaks }}</p>
            <footer> via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago
                {% if child_comment.user == request.user %}
                | <a href="{{ child_comment.get_edit_url }}">Edit</a>
                {% endif %}
                {% if child_comment.user == request.user %}
                | <a href="{{ child_comment.get_delete_url }}">Delete</a>
            {% endif %}
            </footer>
        </blockquote>
        {% endfor %}

    <hr>
</div>
{% endblock content %}

theblog/templates/confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}
{{ title }} |{{ block.super }}
{% endblock title %}

{% block content %}
<div class="col-sm-8 col-sm-offset-2">
        <h1>Confirm delete</h1>
        <form method="post" action=""> {%  csrf_token %}
            <p>Are you sure to delete: "{{ object.content }}" ?</p>
            <input type="submit" value="Confirm" class="btn btn-warning"/>
            <a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
        </form>

    <hr>
</div>
{% endblock content %}

theblog/templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
{{title}} |{{ block.super }}
{% endblock title %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3">
    <h1>{{ title }}</h1>
    <form method="post" action="" enctype="multipart/form-data"> {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-default" type="submit" value="{{ title }}"/>
    </form>
</div>

{% endblock content %}

theblog/templates/messages.html
{% if messages %}
<div class="messages">
    <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
</div>
{% endif %}

theblog/templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
{{title}} |{{ block.super }}
{% endblock title %}

{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}

<div class="col-sm-6">
    <h1>Form</h1>
    <hr>
    <form method="post" action="" enctype="multipart/form-data"> {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="{{ button_name }}"/>

        <a href="
            {% if instance %}
            {{ instance.get_absolute_url }}
            {% else %}
            {% url "posts:list" %}
            {% endif %}" class="btn btn-default">Cancel
        </a>
    </form>
</div>

<div class="col-sm-6">
    <h1>Preview</h1>
    <hr>
    <div class="content-preview">
        <h1 id="preview-title"></h1>
        <p id="preview-content"></p>
    </div>
</div>

{% endblock content %}